events {}

http {
    resolver 127.0.0.11 ipv6=off valid=10s;

    # upstream ai {
    #     server ai-service:8000;
    # }

    server {
        listen 80;

        client_max_body_size 100M;

        # React frontend
        location / {
            set $frontend_upstream frontend:8081;
            proxy_pass http://$frontend_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Express API
        location /api/ {
            set $backend_upstream backend:5000;
            proxy_pass http://$backend_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # # FastAPI AI
        # location /ai/ {
        #     proxy_pass http://ai/;
        #     proxy_set_header Host $host;
        #     proxy_set_header X-Real-IP $remote_addr;
        # }
    }
}